(define (make-check-image)
  (let* ((check-image-height 64)
        (check-image-width 64)
        (buffer (make-u8vector (* check-image-width check-image-height 4) 0)))
    (do ((i 0 (+ i 1))) ((> i check-image-height) buffer)
      (do ((j 0 (+ j 1))) ((> j check-image-width))
        (let ((c (if (or (equal? i 0) (equal? (remainder 64 i) 0)) 255 0)))
          (print c)
          (u8vector-set! buffer (+ (* i j) 0) c)
          (u8vector-set! buffer (+ (* i j) 1) c)
          (u8vector-set! buffer (+ (* i j) 1) c)
          (u8vector-set! buffer (+ (* i j) 3) 255))))))
